# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: UseDotNet@2
  displayName: 'Install .NET 10 SDK'
  inputs:
    version: '10.x'
    includePreviewVersions: true


- task: DotNetCoreCLI@2
  displayName: 'Build and Publish Project'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/MyBestWeb10.csproj' 
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true


- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy to Azure App Service'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'MyAzureConn'        
    appType: 'webAppLinux'
    WebAppName: 'BasicWeb'                  
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'


