# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Starter pipeline

trigger:
- main
- feature/nazar-boncugu-v2

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:


- task: UseDotNet@2
  displayName: 'Install .NET 10 SDK (Preview)'
  inputs:
    packageType: 'sdk'
    version: '10.x'
    includePreviewVersions: true


- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: 'MyBestWeb10/MyBestWeb10.csproj'


- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'MyBestWeb10/MyBestWeb10.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'


- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/MyBestWeb10.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false


- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)' 
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true


- task: AzureRmWebAppDeployment@5
  displayName: 'Deploy to mybestweb10-clean'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'MyAzureConn'
    appType: 'webAppLinux'
    WebAppName: 'mybestweb10-clean'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    DeploymentTypeLinux: 'zipDeploy'